### ISSUE TITLE
Can't you solve this problem with basic image processing?

### ISSUE THREAD

**Issue by DoyleBellamy** [WoXy-Sensei/mammography-breast-detection-YOLOv8#1]
Breasts can be seen clearly in mammography images. Even canny edge detector can identify the breast in the image. Deep learning techniques are typically utilized for more complex issues, hence they are not suitable here.

**Comment by WoXy-Sensei** [comment]
You are right, I achieved successful results using basic image processing methods and worked on different and creative methods other than edge detection. But I wanted to do this from a different perspective, using only a Yolo model, and I wanted to see the results, and I saw that it gave good results.

**Comment by asenakaragoz** [comment]
While basic image processing methods can be effective for mammography images, deep learning techniques like the YOLO model offer high accuracy and flexibility. @WoXy-Sensei  success with YOLO highlights its potential for detecting anomalies in diverse datasets. Using and comparing different methods can lead to more reliable results.
